### ISSUE TITLE
ValueError: scale cannot be an integer: False

### ISSUE THREAD

**Issue by sabaali93** [PJunhyuk/people-counting-classification#6]
I am getting this error when I try to run the code. Below is the full error:
Traceback (most recent call last):
  File "video_tracking.py", line 41, in <module>
    import video_pose
  File "/home/saba/Downloads/people-counting-pose-master/video_pose.py", line 50, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "/home/saba/Downloads/people-counting-pose-master/nnet/predict.py", line 11, in setup_pose_prediction
    outputs = pose_net(cfg).test(inputs)
  File "/home/saba/Downloads/people-counting-pose-master/nnet/pose_net.py", line 90, in test
    heads = self.get_net(inputs)
  File "/home/saba/Downloads/people-counting-pose-master/nnet/pose_net.py", line 86, in get_net
    net, end_points = self.extract_features(inputs)
  File "/home/saba/Downloads/people-counting-pose-master/nnet/pose_net.py", line 54, in extract_features
    with slim.arg_scope(resnet_v1.resnet_arg_scope(False)):
  File "/home/saba/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 257, in resnet_arg_scope
    weights_regularizer=regularizers.l2_regularizer(weight_decay),
  File "/home/saba/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/regularizers.py", line 92, in l2_regularizer
    raise ValueError('scale cannot be an integer: %s' % (scale,))
ValueError: scale cannot be an integer: False

**Comment by Dishcreate** [comment]
@sabaali93 , I got the same issue because I was using python 3.5 version. Then I move to python 3.6 it was fix.

**Comment by PJunhyuk** [comment]
Thanks for feedbacks and solutions!
